# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:48:07+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Path, Query

from models import (
    ActivityEntryForApiContractPartialFindResult,
    ActivityEntryOptionalFields,
    ActivityEntrySortRule,
    AdvancedFilters,
    AlbumForApiContract,
    AlbumForApiContractPartialFindResult,
    AlbumForUserForApiContract,
    AlbumForUserForApiContractPartialFindResult,
    AlbumOptionalFields,
    AlbumReviewContract,
    AlbumSortRule,
    ApiAlbumsIdCommentsGetResponse,
    ApiAlbumsIdReviewsGetResponse,
    ApiAlbumsIdTracksFieldsGetResponse,
    ApiAlbumsIdTracksGetResponse,
    ApiAlbumsIdUserCollectionsGetResponse,
    ApiAlbumsNamesGetResponse,
    ApiAlbumsNewGetResponse,
    ApiAlbumsTopGetResponse,
    ApiArtistsIdCommentsGetResponse,
    ApiArtistsNamesGetResponse,
    ApiDiscussionsFoldersFolderIdTopicsGetResponse,
    ApiDiscussionsFoldersGetResponse,
    ApiEntriesNamesGetResponse,
    ApiReleaseEventsEventIdAlbumsGetResponse,
    ApiReleaseEventsEventIdPublishedSongsGetResponse,
    ApiReleaseEventsNamesGetResponse,
    ApiResourcesCultureCodeGetResponse,
    ApiSongListsFeaturedNamesGetResponse,
    ApiSongsHighlightedGetResponse,
    ApiSongsIdCommentsGetResponse,
    ApiSongsIdDerivedGetResponse,
    ApiSongsIdRatingsGetResponse,
    ApiSongsNamesGetResponse,
    ApiSongsTopRatedGetResponse,
    ApiTagsCategoryNamesGetResponse,
    ApiTagsNamesGetResponse,
    ApiTagsTagIdChildrenGetResponse,
    ApiTagsTopGetResponse,
    ApiUsersIdEventsGetResponse,
    ApiUsersNamesGetResponse,
    ArtistAlbumParticipationStatus,
    ArtistForApiContract,
    ArtistForApiContractPartialFindResult,
    ArtistForUserForApiContract,
    ArtistForUserForApiContractPartialFindResult,
    ArtistId,
    ArtistOptionalFields,
    ArtistRelationsFields,
    ArtistSortRule,
    ArtistType,
    CommentForApiContract,
    CommentForApiContractPartialFindResult,
    CommentOptionalFields,
    CommentSortRule,
    ContentLanguagePreference,
    CreateReportModel,
    DiscType,
    DiscussionFolderContract,
    DiscussionFolderOptionalFields,
    DiscussionTopicContract,
    DiscussionTopicContractPartialFindResult,
    DiscussionTopicOptionalFields,
    DiscussionTopicSortRule,
    DistanceUnit,
    EntryEditDataContract,
    EntryEditEvent,
    EntryForApiContractPartialFindResult,
    EntryOptionalFields,
    EntrySortRule,
    EntryStatus,
    EntryType,
    EntryTypes,
    EventCategory,
    EventReportType,
    EventSortRule,
    FieldModel,
    IgnoreIds,
    LogicalGrouping,
    LyricsForSongContract,
    MediaType,
    MessageId,
    NameMatchMode,
    PurchaseStatus,
    PurchaseStatuses,
    PVForSongContractPartialFindResult,
    PVService,
    PVServices,
    RatedSongForUserForApiContractPartialFindResult,
    RatedSongForUserSortRule,
    RelatedSongsContract,
    ReleaseEventForApiContract,
    ReleaseEventForApiContractPartialFindResult,
    ReleaseEventOptionalFields,
    ReleaseEventSeriesForApiContract,
    ReleaseEventSeriesForApiContractPartialFindResult,
    ReleaseEventSeriesForEditForApiContract,
    ReleaseEventSeriesOptionalFields,
    SetNames,
    SongForApiContract,
    SongForApiContractPartialFindResult,
    SongInListForApiContractPartialFindResult,
    SongListFeaturedCategory,
    SongListForApiContractPartialFindResult,
    SongListForEditForApiContract,
    SongListOptionalFields,
    SongListSortRule,
    SongOptionalFields,
    SongRatingContract,
    SongSortRule,
    SongVocalistSelection,
    SongVoteRating,
    SortDirection,
    TagBaseContract,
    TagForApiContract,
    TagForApiContractPartialFindResult,
    TagId,
    TagName,
    TagOptionalFields,
    TagReportType,
    TagSortRule,
    TagTargetTypes,
    TopSongsDateFilterType,
    UserEventRelationshipType,
    UserForApiContract,
    UserForApiContractPartialFindResult,
    UserGroupId,
    UserInboxType,
    UserMessageContract,
    UserMessageContractPartialFindResult,
    UserOptionalFields,
    UserSortRule,
    VenueForApiContractPartialFindResult,
    VenueOptionalFields,
    VenueReportType,
    VenueSortRule,
)

app = MCPProxy(
    contact={'x-twitter': 'vocadb'},
    title='VocaDbWeb',
    version='1.0',
)


@app.get(
    '/api/activityEntries', tags=['activity_entry_management', 'entry_data_management']
)
def get_api_activity_entries(
    before: Optional[datetime] = None,
    since: Optional[datetime] = None,
    user_id: Optional[int] = Query(None, alias='userId'),
    edit_event: Optional[EntryEditEvent] = Query(None, alias='editEvent'),
    entry_type: Optional[EntryType] = Query(None, alias='entryType'),
    max_results: Optional[int] = Query(50, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    fields: Optional[ActivityEntryOptionalFields] = None,
    entry_fields: Optional[EntryOptionalFields] = Query(None, alias='entryFields'),
    lang: Optional[ContentLanguagePreference] = None,
    sort_rule: Optional[ActivityEntrySortRule] = Query(None, alias='sortRule'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/albums', tags=['album_management', 'entry_data_management', 'tag_operations']
)
def get_api_albums(
    query: Optional[str] = '',
    disc_types: Optional[DiscType] = Query(None, alias='discTypes'),
    tag_name__: Optional[TagName] = Query(None, alias='tagName[]'),
    tag_id__: Optional[TagId] = Query(None, alias='tagId[]'),
    child_tags: Optional[bool] = Query(False, alias='childTags'),
    artist_id__: Optional[ArtistId] = Query(None, alias='artistId[]'),
    artist_participation_status: Optional[ArtistAlbumParticipationStatus] = Query(
        None, alias='artistParticipationStatus'
    ),
    child_voicebanks: Optional[bool] = Query(False, alias='childVoicebanks'),
    include_members: Optional[bool] = Query(False, alias='includeMembers'),
    barcode: Optional[str] = None,
    status: Optional[EntryStatus] = None,
    release_date_after: Optional[datetime] = Query(None, alias='releaseDateAfter'),
    release_date_before: Optional[datetime] = Query(None, alias='releaseDateBefore'),
    advanced_filters: Optional[AdvancedFilters] = Query(None, alias='advancedFilters'),
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    sort: Optional[AlbumSortRule] = None,
    prefer_accurate_matches: Optional[bool] = Query(
        False, alias='preferAccurateMatches'
    ),
    deleted: Optional[bool] = False,
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    fields: Optional[AlbumOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/albums/comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def delete_api_albums_comments__comment_id(
    comment_id: int = Path(..., alias='commentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/albums/comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_albums_comments__comment_id(
    comment_id: int = Path(..., alias='commentId'), body: CommentForApiContract = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/albums/names', tags=['entry_data_management'])
def get_api_albums_names(
    query: Optional[str] = '',
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    max_results: Optional[int] = Query(15, alias='maxResults'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/albums/new', tags=['album_management', 'user_album_management'])
def get_api_albums_new(
    language_preference: Optional[ContentLanguagePreference] = Query(
        None, alias='languagePreference'
    ),
    fields: Optional[AlbumOptionalFields] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/albums/top', tags=['album_management', 'user_album_management'])
def get_api_albums_top(
    ignore_ids__: Optional[IgnoreIds] = Query(None, alias='ignoreIds[]'),
    language_preference: Optional[ContentLanguagePreference] = Query(
        None, alias='languagePreference'
    ),
    fields: Optional[AlbumOptionalFields] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/api/albums/{id}', tags=['user_message_management', 'comment_control'])
def delete_api_albums__id(id: int, notes: Optional[str] = ''):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/albums/{id}', tags=['album_management', 'song_service'])
def get_api_albums__id(
    id: int,
    fields: Optional[AlbumOptionalFields] = None,
    song_fields: Optional[SongOptionalFields] = Query(None, alias='songFields'),
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/albums/{id}/comments',
    tags=['activity_entry_management', 'entry_data_management'],
)
def get_api_albums__id_comments(id: int):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/albums/{id}/comments',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_albums__id_comments(id: int, body: CommentForApiContract = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/albums/{id}/reviews', tags=['cultural_resource_management'])
def get_api_albums__id_reviews(
    id: int, language_code: Optional[str] = Query(None, alias='languageCode')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/api/albums/{id}/reviews', tags=['album_management', 'comment_control'])
def post_api_albums__id_reviews(id: int, body: AlbumReviewContract = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/albums/{id}/reviews/{reviewId}', tags=['comment_control', 'album_management']
)
def delete_api_albums__id_reviews__review_id(
    review_id: int = Path(..., alias='reviewId'), id: str = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/albums/{id}/tracks', tags=['song_service', 'individual_song_list_management']
)
def get_api_albums__id_tracks(
    id: int,
    fields: Optional[SongOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/albums/{id}/tracks/fields', tags=['entry_data_management', 'album_management']
)
def get_api_albums__id_tracks_fields(
    id: int,
    field__: Optional[FieldModel] = Query(None, alias='field[]'),
    disc_number: Optional[int] = Query(None, alias='discNumber'),
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/albums/{id}/user-collections', tags=['cultural_resource_management'])
def get_api_albums__id_user_collections(
    id: int,
    language_preference: Optional[ContentLanguagePreference] = Query(
        None, alias='languagePreference'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/artists',
    tags=['artist_profile_management', 'entry_data_management', 'tag_operations'],
)
def get_api_artists(
    query: Optional[str] = '',
    artist_types: Optional[str] = Query(None, alias='artistTypes'),
    allow_base_voicebanks: Optional[bool] = Query(True, alias='allowBaseVoicebanks'),
    tag_name__: Optional[TagName] = Query(None, alias='tagName[]'),
    tag_id__: Optional[TagId] = Query(None, alias='tagId[]'),
    child_tags: Optional[bool] = Query(False, alias='childTags'),
    followed_by_user_id: Optional[int] = Query(None, alias='followedByUserId'),
    status: Optional[EntryStatus] = None,
    advanced_filters: Optional[AdvancedFilters] = Query(None, alias='advancedFilters'),
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    sort: Optional[ArtistSortRule] = None,
    prefer_accurate_matches: Optional[bool] = Query(
        False, alias='preferAccurateMatches'
    ),
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    fields: Optional[ArtistOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/artists/comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def delete_api_artists_comments__comment_id(
    comment_id: int = Path(..., alias='commentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/artists/comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_artists_comments__comment_id(
    comment_id: int = Path(..., alias='commentId'), body: CommentForApiContract = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/artists/names', tags=['entry_data_management'])
def get_api_artists_names(
    query: Optional[str] = '',
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    max_results: Optional[int] = Query(15, alias='maxResults'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/artists/{id}', tags=['comment_control', 'discussion_comment_moderation']
)
def delete_api_artists__id(id: int, notes: Optional[str] = ''):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/artists/{id}', tags=['artist_profile_management'])
def get_api_artists__id(
    id: int,
    fields: Optional[ArtistOptionalFields] = None,
    relations: Optional[ArtistRelationsFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/artists/{id}/comments', tags=['entry_data_management'])
def get_api_artists__id_comments(id: int):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/artists/{id}/comments',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_artists__id_comments(id: int, body: CommentForApiContract = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/comments',
    tags=['activity_entry_management', 'entry_data_management', 'comment_control'],
)
def get_api_comments(
    before: Optional[datetime] = None,
    since: Optional[datetime] = None,
    user_id: Optional[int] = Query(None, alias='userId'),
    entry_type: Optional[EntryType] = Query(None, alias='entryType'),
    max_results: Optional[int] = Query(50, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    fields: Optional[CommentOptionalFields] = None,
    entry_fields: Optional[EntryOptionalFields] = Query(None, alias='entryFields'),
    lang: Optional[ContentLanguagePreference] = None,
    sort_rule: Optional[CommentSortRule] = Query(None, alias='sortRule'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/comments/{entryType}-comments', tags=['entry_data_management'])
def get_api_comments__entry_type_comments(
    entry_type: EntryType = Path(..., alias='entryType'),
    entry_id: Optional[int] = Query(None, alias='entryId'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/comments/{entryType}-comments',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_comments__entry_type_comments(
    entry_type: EntryType = Path(..., alias='entryType'),
    body: CommentForApiContract = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/comments/{entryType}-comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation', 'entry_data_management'],
)
def delete_api_comments__entry_type_comments__comment_id(
    entry_type: EntryType = Path(..., alias='entryType'),
    comment_id: int = Path(..., alias='commentId'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/comments/{entryType}-comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_comments__entry_type_comments__comment_id(
    entry_type: EntryType = Path(..., alias='entryType'),
    comment_id: int = Path(..., alias='commentId'),
    body: CommentForApiContract = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/discussions/comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def delete_api_discussions_comments__comment_id(
    comment_id: int = Path(..., alias='commentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/discussions/comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_discussions_comments__comment_id(
    comment_id: int = Path(..., alias='commentId'), body: CommentForApiContract = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/discussions/folders', tags=['discussion_folder_management'])
def get_api_discussions_folders(
    fields: Optional[DiscussionFolderOptionalFields] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/discussions/folders',
    tags=['discussion_folder_management', 'discussion_topic_management'],
)
def post_api_discussions_folders(body: DiscussionFolderContract = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/discussions/folders/{folderId}/topics',
    tags=['discussion_folder_management', 'discussion_topic_management'],
)
def get_api_discussions_folders__folder_id_topics(
    folder_id: int = Path(..., alias='folderId'),
    fields: Optional[DiscussionTopicOptionalFields] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/discussions/folders/{folderId}/topics',
    tags=['discussion_folder_management', 'discussion_topic_management'],
)
def post_api_discussions_folders__folder_id_topics(
    folder_id: int = Path(..., alias='folderId'), body: DiscussionTopicContract = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/discussions/topics',
    tags=['discussion_folder_management', 'discussion_topic_management'],
)
def get_api_discussions_topics(
    folder_id: Optional[int] = Query(None, alias='folderId'),
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    sort: Optional[DiscussionTopicSortRule] = None,
    fields: Optional[DiscussionTopicOptionalFields] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/api/discussions/topics/{topicId}', tags=['discussion_topic_management'])
def delete_api_discussions_topics__topic_id(topic_id: int = Path(..., alias='topicId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/discussions/topics/{topicId}',
    tags=['discussion_topic_management', 'discussion_comment_moderation'],
)
def get_api_discussions_topics__topic_id(
    topic_id: int = Path(..., alias='topicId'),
    fields: Optional[DiscussionTopicOptionalFields] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/discussions/topics/{topicId}',
    tags=['discussion_topic_management', 'discussion_comment_moderation'],
)
def post_api_discussions_topics__topic_id(
    topic_id: int = Path(..., alias='topicId'), body: DiscussionTopicContract = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/discussions/topics/{topicId}/comments',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_discussions_topics__topic_id_comments(
    topic_id: int = Path(..., alias='topicId'), body: CommentForApiContract = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/entries', tags=['activity_entry_management', 'entry_data_management'])
def get_api_entries(
    query: Optional[str] = '',
    tag_name__: Optional[TagName] = Query(None, alias='tagName[]'),
    tag_id__: Optional[TagId] = Query(None, alias='tagId[]'),
    child_tags: Optional[bool] = Query(False, alias='childTags'),
    entry_types: Optional[EntryTypes] = Query(None, alias='entryTypes'),
    status: Optional[EntryStatus] = None,
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    sort: Optional[EntrySortRule] = None,
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    fields: Optional[EntryOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/entries/names', tags=['entry_data_management'])
def get_api_entries_names(
    query: Optional[str] = '',
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    max_results: Optional[int] = Query(10, alias='maxResults'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/entry-types/{entryType}/{subType}/tag', tags=['entry_data_management'])
def get_api_entry_types__entry_type__sub_type_tag(
    entry_type: EntryType = Path(..., alias='entryType'),
    sub_type: str = Path(..., alias='subType'),
    fields: Optional[TagOptionalFields] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/pvs/for-songs', tags=['activity_entry_management', 'entry_data_management']
)
def get_api_pvs_for_songs(
    name: Optional[str] = None,
    author: Optional[str] = None,
    service: Optional[PVService] = None,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/releaseEventSeries', tags=['release_event_handling', 'entry_data_management']
)
def get_api_release_event_series(
    query: Optional[str] = '',
    fields: Optional[ReleaseEventSeriesOptionalFields] = None,
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/releaseEventSeries/{id}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def delete_api_release_event_series__id(
    id: int,
    notes: Optional[str] = '',
    hard_delete: Optional[bool] = Query(False, alias='hardDelete'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/releaseEventSeries/{id}', tags=['release_event_handling'])
def get_api_release_event_series__id(
    id: int,
    fields: Optional[ReleaseEventSeriesOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/releaseEventSeries/{id}/for-edit', tags=['entry_data_management'])
def get_api_release_event_series__id_for_edit(id: int):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/releaseEvents',
    tags=[
        'activity_entry_management',
        'release_event_handling',
        'entry_data_management',
    ],
)
def get_api_release_events(
    query: Optional[str] = '',
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    series_id: Optional[int] = Query(0, alias='seriesId'),
    after_date: Optional[datetime] = Query(None, alias='afterDate'),
    before_date: Optional[datetime] = Query(None, alias='beforeDate'),
    category: Optional[EventCategory] = None,
    user_collection_id: Optional[int] = Query(None, alias='userCollectionId'),
    tag_id__: Optional[TagId] = Query(None, alias='tagId[]'),
    child_tags: Optional[bool] = Query(False, alias='childTags'),
    artist_id__: Optional[ArtistId] = Query(None, alias='artistId[]'),
    child_voicebanks: Optional[bool] = Query(False, alias='childVoicebanks'),
    include_members: Optional[bool] = Query(False, alias='includeMembers'),
    status: Optional[EntryStatus] = None,
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    sort: Optional[EventSortRule] = None,
    fields: Optional[ReleaseEventOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
    sort_direction: Optional[SortDirection] = Query(None, alias='sortDirection'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/releaseEvents/names', tags=['entry_data_management'])
def get_api_release_events_names(
    query: Optional[str] = '',
    max_results: Optional[int] = Query(10, alias='maxResults'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/releaseEvents/{eventId}/albums',
    tags=['release_event_handling', 'album_management'],
)
def get_api_release_events__event_id_albums(
    event_id: int = Path(..., alias='eventId'),
    fields: Optional[AlbumOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/releaseEvents/{eventId}/published-songs',
    tags=['release_event_handling', 'entry_data_management'],
)
def get_api_release_events__event_id_published_songs(
    event_id: int = Path(..., alias='eventId'),
    fields: Optional[SongOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/releaseEvents/{eventId}/reports',
    tags=['release_event_handling', 'user_reporting_service'],
)
def post_api_release_events__event_id_reports(
    event_id: int = Path(..., alias='eventId'),
    report_type: Optional[EventReportType] = Query(None, alias='reportType'),
    notes: Optional[str] = None,
    version_number: Optional[int] = Query(None, alias='versionNumber'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/releaseEvents/{id}', tags=['comment_control', 'discussion_comment_moderation']
)
def delete_api_release_events__id(
    id: int,
    notes: Optional[str] = '',
    hard_delete: Optional[bool] = Query(False, alias='hardDelete'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/releaseEvents/{id}', tags=['release_event_handling'])
def get_api_release_events__id(
    id: int,
    fields: Optional[ReleaseEventOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/resources/{cultureCode}', tags=['cultural_resource_management'])
def get_api_resources__culture_code(
    culture_code: str = Path(..., alias='cultureCode'),
    set_names__: Optional[SetNames] = Query(None, alias='setNames[]'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/songLists', tags=['song_list_operations', 'individual_song_list_management']
)
def post_api_song_lists(body: SongListForEditForApiContract = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/songLists/comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def delete_api_song_lists_comments__comment_id(
    comment_id: int = Path(..., alias='commentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/songLists/comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_song_lists_comments__comment_id(
    comment_id: int = Path(..., alias='commentId'), body: CommentForApiContract = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/songLists/featured',
    tags=['song_list_operations', 'individual_song_list_management', 'tag_operations'],
)
def get_api_song_lists_featured(
    query: Optional[str] = '',
    tag_id__: Optional[TagId] = Query(None, alias='tagId[]'),
    child_tags: Optional[bool] = Query(False, alias='childTags'),
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    featured_category: Optional[SongListFeaturedCategory] = Query(
        None, alias='featuredCategory'
    ),
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    sort: Optional[SongListSortRule] = None,
    fields: Optional[SongListOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/songLists/featured/names',
    tags=['song_list_operations', 'individual_song_list_management'],
)
def get_api_song_lists_featured_names(
    query: Optional[str] = '',
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    featured_category: Optional[SongListFeaturedCategory] = Query(
        None, alias='featuredCategory'
    ),
    max_results: Optional[int] = Query(10, alias='maxResults'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/songLists/{id}', tags=['comment_control', 'discussion_comment_moderation']
)
def delete_api_song_lists__id(
    id: int,
    notes: Optional[str] = '',
    hard_delete: Optional[bool] = Query(False, alias='hardDelete'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/songLists/{listId}/comments',
    tags=[
        'album_management',
        'artist_profile_management',
        'individual_song_list_management',
        'user_music_management',
    ],
)
def get_api_song_lists__list_id_comments(list_id: int = Path(..., alias='listId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/songLists/{listId}/comments',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_song_lists__list_id_comments(
    list_id: int = Path(..., alias='listId'), body: CommentForApiContract = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/songLists/{listId}/songs',
    tags=['song_list_operations', 'individual_song_list_management', 'song_service'],
)
def get_api_song_lists__list_id_songs(
    list_id: int = Path(..., alias='listId'),
    query: Optional[str] = '',
    song_types: Optional[str] = Query(None, alias='songTypes'),
    pv_services: Optional[PVServices] = Query(None, alias='pvServices'),
    tag_id__: Optional[TagId] = Query(None, alias='tagId[]'),
    artist_id__: Optional[ArtistId] = Query(None, alias='artistId[]'),
    child_voicebanks: Optional[bool] = Query(False, alias='childVoicebanks'),
    advanced_filters: Optional[AdvancedFilters] = Query(None, alias='advancedFilters'),
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    sort: Optional[SongSortRule] = None,
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    fields: Optional[SongOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/songs', tags=['entry_data_management', 'song_service', 'tag_operations'])
def get_api_songs(
    query: Optional[str] = '',
    song_types: Optional[str] = Query(None, alias='songTypes'),
    after_date: Optional[datetime] = Query(None, alias='afterDate'),
    before_date: Optional[datetime] = Query(None, alias='beforeDate'),
    tag_name__: Optional[TagName] = Query(None, alias='tagName[]'),
    tag_id__: Optional[TagId] = Query(None, alias='tagId[]'),
    child_tags: Optional[bool] = Query(False, alias='childTags'),
    unify_types_and_tags: Optional[bool] = Query(False, alias='unifyTypesAndTags'),
    artist_id__: Optional[ArtistId] = Query(None, alias='artistId[]'),
    artist_participation_status: Optional[ArtistAlbumParticipationStatus] = Query(
        None, alias='artistParticipationStatus'
    ),
    child_voicebanks: Optional[bool] = Query(False, alias='childVoicebanks'),
    include_members: Optional[bool] = Query(False, alias='includeMembers'),
    only_with_pvs: Optional[bool] = Query(False, alias='onlyWithPvs'),
    pv_services: Optional[PVServices] = Query(None, alias='pvServices'),
    since: Optional[int] = None,
    min_score: Optional[int] = Query(None, alias='minScore'),
    user_collection_id: Optional[int] = Query(None, alias='userCollectionId'),
    release_event_id: Optional[int] = Query(None, alias='releaseEventId'),
    parent_song_id: Optional[int] = Query(None, alias='parentSongId'),
    status: Optional[EntryStatus] = None,
    advanced_filters: Optional[AdvancedFilters] = Query(None, alias='advancedFilters'),
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    sort: Optional[SongSortRule] = None,
    prefer_accurate_matches: Optional[bool] = Query(
        False, alias='preferAccurateMatches'
    ),
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    fields: Optional[SongOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
    min_milli_bpm: Optional[int] = Query(None, alias='minMilliBpm'),
    max_milli_bpm: Optional[int] = Query(None, alias='maxMilliBpm'),
    min_length: Optional[int] = Query(None, alias='minLength'),
    max_length: Optional[int] = Query(None, alias='maxLength'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/songs/byPv', tags=['individual_song_list_management', 'song_service'])
def get_api_songs_by_pv(
    pv_service: Optional[PVService] = Query(None, alias='pvService'),
    pv_id: Optional[str] = Query(None, alias='pvId'),
    fields: Optional[SongOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/songs/comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def delete_api_songs_comments__comment_id(
    comment_id: int = Path(..., alias='commentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/songs/comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_songs_comments__comment_id(
    comment_id: int = Path(..., alias='commentId'), body: CommentForApiContract = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/songs/highlighted', tags=['cultural_resource_management'])
def get_api_songs_highlighted(
    language_preference: Optional[ContentLanguagePreference] = Query(
        None, alias='languagePreference'
    ),
    fields: Optional[SongOptionalFields] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/songs/lyrics/{lyricsId}', tags=['entry_data_management'])
def get_api_songs_lyrics__lyrics_id(lyrics_id: int = Path(..., alias='lyricsId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/songs/names', tags=['entry_data_management'])
def get_api_songs_names(
    query: Optional[str] = '',
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    max_results: Optional[int] = Query(15, alias='maxResults'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/songs/top-rated',
    tags=['song_service', 'individual_song_list_management', 'entry_data_management'],
)
def get_api_songs_top_rated(
    duration_hours: Optional[int] = Query(None, alias='durationHours'),
    start_date: Optional[datetime] = Query(None, alias='startDate'),
    filter_by: Optional[TopSongsDateFilterType] = Query(None, alias='filterBy'),
    vocalist: Optional[SongVocalistSelection] = None,
    max_results: Optional[int] = Query(25, alias='maxResults'),
    fields: Optional[SongOptionalFields] = None,
    language_preference: Optional[ContentLanguagePreference] = Query(
        None, alias='languagePreference'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/songs/{id}', tags=['comment_control', 'discussion_comment_moderation']
)
def delete_api_songs__id(id: int, notes: Optional[str] = ''):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/songs/{id}', tags=['song_service', 'individual_song_list_management'])
def get_api_songs__id(
    id: int,
    fields: Optional[SongOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/songs/{id}/comments',
    tags=['activity_entry_management', 'entry_data_management'],
)
def get_api_songs__id_comments(id: int):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/songs/{id}/comments',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_songs__id_comments(id: int, body: CommentForApiContract = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/songs/{id}/derived', tags=['song_service'])
def get_api_songs__id_derived(
    id: int,
    fields: Optional[SongOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/songs/{id}/ratings',
    tags=['user_profile_data_management', 'user_account_management'],
)
def get_api_songs__id_ratings(
    id: int,
    user_fields: Optional[UserOptionalFields] = Query(None, alias='userFields'),
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/api/songs/{id}/ratings', tags=['song_service', 'user_music_management'])
def post_api_songs__id_ratings(id: int, body: SongRatingContract = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/songs/{id}/related',
    tags=['song_service', 'individual_song_list_management', 'entry_data_management'],
)
def get_api_songs__id_related(
    id: int,
    fields: Optional[SongOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/tags', tags=['entry_data_management', 'tag_operations'])
def get_api_tags(
    query: Optional[str] = '',
    allow_children: Optional[bool] = Query(True, alias='allowChildren'),
    category_name: Optional[str] = Query('', alias='categoryName'),
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    sort: Optional[TagSortRule] = None,
    prefer_accurate_matches: Optional[bool] = Query(
        False, alias='preferAccurateMatches'
    ),
    fields: Optional[TagOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
    target: Optional[TagTargetTypes] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/api/tags', tags=['user_account_management'])
def post_api_tags(name: Optional[str] = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/tags/byName/{name}',
    tags=['user_profile_data_management', 'user_profile_operations'],
)
def get_api_tags_by_name__name(
    name: str,
    fields: Optional[TagOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/tags/categoryNames', tags=['entry_data_management'])
def get_api_tags_category_names(
    query: Optional[str] = '',
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/tags/comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def delete_api_tags_comments__comment_id(
    comment_id: int = Path(..., alias='commentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/tags/comments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_tags_comments__comment_id(
    comment_id: int = Path(..., alias='commentId'), body: CommentForApiContract = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/tags/names', tags=['entry_data_management'])
def get_api_tags_names(
    query: Optional[str] = '',
    allow_aliases: Optional[bool] = Query(True, alias='allowAliases'),
    max_results: Optional[int] = Query(10, alias='maxResults'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/tags/top', tags=['entry_data_management', 'activity_entry_management'])
def get_api_tags_top(
    category_name: Optional[str] = Query(None, alias='categoryName'),
    entry_type: Optional[EntryType] = Query(None, alias='entryType'),
    max_results: Optional[int] = Query(15, alias='maxResults'),
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/api/tags/{id}', tags=['comment_control', 'discussion_comment_moderation'])
def delete_api_tags__id(
    id: int,
    notes: Optional[str] = '',
    hard_delete: Optional[bool] = Query(False, alias='hardDelete'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/tags/{id}', tags=['entry_data_management'])
def get_api_tags__id(
    id: int,
    fields: Optional[TagOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/tags/{tagId}/children', tags=['tag_operations'])
def get_api_tags__tag_id_children(
    tag_id: int = Path(..., alias='tagId'),
    fields: Optional[TagOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/tags/{tagId}/comments', tags=['tag_operations'])
def get_api_tags__tag_id_comments(tag_id: int = Path(..., alias='tagId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/tags/{tagId}/comments',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_tags__tag_id_comments(
    tag_id: int = Path(..., alias='tagId'), body: CommentForApiContract = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/api/tags/{tagId}/reports', tags=['tag_operations'])
def post_api_tags__tag_id_reports(
    tag_id: int = Path(..., alias='tagId'),
    report_type: Optional[TagReportType] = Query(None, alias='reportType'),
    notes: Optional[str] = None,
    version_number: Optional[int] = Query(None, alias='versionNumber'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users',
    tags=[
        'user_account_management',
        'user_profile_data_management',
        'user_profile_operations',
    ],
)
def get_api_users(
    query: Optional[str] = '',
    groups: Optional[UserGroupId] = None,
    join_date_after: Optional[datetime] = Query(None, alias='joinDateAfter'),
    join_date_before: Optional[datetime] = Query(None, alias='joinDateBefore'),
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    sort: Optional[UserSortRule] = None,
    include_disabled: Optional[bool] = Query(False, alias='includeDisabled'),
    only_verified: Optional[bool] = Query(False, alias='onlyVerified'),
    knows_language: Optional[str] = Query(None, alias='knowsLanguage'),
    fields: Optional[UserOptionalFields] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/current',
    tags=['user_profile_data_management', 'user_profile_operations'],
)
def get_api_users_current(fields: Optional[UserOptionalFields] = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/current/album-collection-statuses/{albumId}', tags=['album_management']
)
def get_api_users_current_album_collection_statuses__album_id(
    album_id: int = Path(..., alias='albumId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/users/current/albums/{albumId}',
    tags=['album_management', 'user_album_management'],
)
def post_api_users_current_albums__album_id(
    album_id: int = Path(..., alias='albumId'),
    collection_status: Optional[PurchaseStatus] = Query(None, alias='collectionStatus'),
    media_type: Optional[MediaType] = Query(None, alias='mediaType'),
    rating: Optional[int] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/current/followedArtists/{artistId}', tags=['artist_profile_management']
)
def get_api_users_current_followed_artists__artist_id(
    artist_id: int = Path(..., alias='artistId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/api/users/current/followedTags/{tagId}', tags=['tag_operations'])
def delete_api_users_current_followed_tags__tag_id(
    tag_id: int = Path(..., alias='tagId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/api/users/current/followedTags/{tagId}', tags=['tag_operations'])
def post_api_users_current_followed_tags__tag_id(
    tag_id: int = Path(..., alias='tagId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/users/current/ratedSongs/{songId}', tags=['song_service'])
def get_api_users_current_rated_songs__song_id(
    song_id: int = Path(..., alias='songId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/users/current/refreshEntryEdit',
    tags=['entry_data_management', 'activity_entry_management'],
)
def post_api_users_current_refresh_entry_edit(
    entry_type: Optional[EntryType] = Query(None, alias='entryType'),
    entry_id: Optional[int] = Query(None, alias='entryId'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/users/current/songTags/{songId}',
    tags=['song_service', 'individual_song_list_management', 'song_list_operations'],
)
def post_api_users_current_song_tags__song_id(song_id: int = Path(..., alias='songId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/users/messages/{messageId}', tags=['user_message_management'])
def get_api_users_messages__message_id(message_id: int = Path(..., alias='messageId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/users/names', tags=['entry_data_management'])
def get_api_users_names(
    query: Optional[str] = '',
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    max_results: Optional[int] = Query(10, alias='maxResults'),
    include_disabled: Optional[bool] = Query(False, alias='includeDisabled'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/users/profileComments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def delete_api_users_profile_comments__comment_id(
    comment_id: int = Path(..., alias='commentId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/users/profileComments/{commentId}',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_users_profile_comments__comment_id(
    comment_id: int = Path(..., alias='commentId'), body: CommentForApiContract = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/{id}',
    tags=[
        'user_profile_data_management',
        'user_account_management',
        'user_profile_operations',
    ],
)
def get_api_users__id(id: int, fields: Optional[UserOptionalFields] = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/{id}/album-collection-statuses/{albumId}', tags=['album_management']
)
def get_api_users__id_album_collection_statuses__album_id(
    id: int, album_id: int = Path(..., alias='albumId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/{id}/albums',
    tags=['album_management', 'release_event_handling', 'tag_operations'],
)
def get_api_users__id_albums(
    id: int,
    query: Optional[str] = '',
    tag_id: Optional[int] = Query(None, alias='tagId'),
    tag: Optional[str] = None,
    artist_id: Optional[int] = Query(None, alias='artistId'),
    purchase_statuses: Optional[PurchaseStatuses] = Query(
        None, alias='purchaseStatuses'
    ),
    release_event_id: Optional[int] = Query(0, alias='releaseEventId'),
    album_types: Optional[DiscType] = Query(None, alias='albumTypes'),
    advanced_filters: Optional[AdvancedFilters] = Query(None, alias='advancedFilters'),
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    sort: Optional[AlbumSortRule] = None,
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    fields: Optional[AlbumOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
    media_type: Optional[MediaType] = Query(None, alias='mediaType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/{id}/events',
    tags=[
        'user_account_management',
        'user_profile_data_management',
        'user_profile_operations',
    ],
)
def get_api_users__id_events(
    id: int,
    relationship_type: Optional[UserEventRelationshipType] = Query(
        None, alias='relationshipType'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/{id}/followedArtists',
    tags=['artist_profile_management', 'entry_data_management', 'tag_operations'],
)
def get_api_users__id_followed_artists(
    id: int,
    query: Optional[str] = '',
    tag_id__: Optional[TagId] = Query(None, alias='tagId[]'),
    artist_type: Optional[ArtistType] = Query(None, alias='artistType'),
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    sort: Optional[ArtistSortRule] = None,
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    fields: Optional[ArtistOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/{id}/followedArtists/{artistId}', tags=['artist_profile_management']
)
def get_api_users__id_followed_artists__artist_id(
    id: int, artist_id: int = Path(..., alias='artistId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/api/users/{id}/messages', tags=['user_message_management'])
def delete_api_users__id_messages(
    id: int, message_id: Optional[MessageId] = Query(None, alias='messageId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/{id}/messages',
    tags=[
        'user_message_management',
        'user_account_management',
        'user_profile_data_management',
    ],
)
def get_api_users__id_messages(
    id: int,
    inbox: Optional[UserInboxType] = None,
    unread: Optional[bool] = False,
    another_user_id: Optional[int] = Query(None, alias='anotherUserId'),
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/api/users/{id}/messages', tags=['user_message_management'])
def post_api_users__id_messages(id: int, body: UserMessageContract = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/{id}/profileComments',
    tags=['activity_entry_management', 'entry_data_management'],
)
def get_api_users__id_profile_comments(
    id: int,
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/users/{id}/profileComments',
    tags=['comment_control', 'discussion_comment_moderation'],
)
def post_api_users__id_profile_comments(id: int, body: CommentForApiContract = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/{id}/ratedSongs',
    tags=['song_service', 'tag_operations', 'user_music_management'],
)
def get_api_users__id_rated_songs(
    id: int,
    query: Optional[str] = '',
    tag_name: Optional[str] = Query(None, alias='tagName'),
    tag_id__: Optional[TagId] = Query(None, alias='tagId[]'),
    artist_id__: Optional[ArtistId] = Query(None, alias='artistId[]'),
    child_voicebanks: Optional[bool] = Query(False, alias='childVoicebanks'),
    artist_grouping: Optional[LogicalGrouping] = Query(None, alias='artistGrouping'),
    rating: Optional[SongVoteRating] = None,
    song_list_id: Optional[int] = Query(None, alias='songListId'),
    group_by_rating: Optional[bool] = Query(True, alias='groupByRating'),
    pv_services: Optional[PVServices] = Query(None, alias='pvServices'),
    advanced_filters: Optional[AdvancedFilters] = Query(None, alias='advancedFilters'),
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    sort: Optional[RatedSongForUserSortRule] = None,
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    fields: Optional[SongOptionalFields] = None,
    lang: Optional[ContentLanguagePreference] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/{id}/ratedSongs/{songId}',
    tags=['song_service', 'individual_song_list_management'],
)
def get_api_users__id_rated_songs__song_id(
    id: int, song_id: int = Path(..., alias='songId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/api/users/{id}/reports', tags=['user_reporting_service'])
def post_api_users__id_reports(id: int, body: CreateReportModel = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/api/users/{id}/settings/{settingName}', tags=['user_profile_operations'])
def post_api_users__id_settings__setting_name(
    id: int, setting_name: str = Path(..., alias='settingName'), body: str = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/users/{id}/songLists',
    tags=[
        'song_list_operations',
        'tag_operations',
        'entry_data_management',
        'individual_song_list_management',
    ],
)
def get_api_users__id_song_lists(
    id: int,
    query: Optional[str] = '',
    tag_id__: Optional[TagId] = Query(None, alias='tagId[]'),
    child_tags: Optional[bool] = Query(False, alias='childTags'),
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    sort: Optional[SongListSortRule] = None,
    fields: Optional[SongListOptionalFields] = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/venues', tags=['venue_information_management', 'entry_data_management'])
def get_api_venues(
    query: Optional[str] = '',
    fields: Optional[VenueOptionalFields] = None,
    start: Optional[int] = 0,
    max_results: Optional[int] = Query(10, alias='maxResults'),
    get_total_count: Optional[bool] = Query(False, alias='getTotalCount'),
    name_match_mode: Optional[NameMatchMode] = Query(None, alias='nameMatchMode'),
    lang: Optional[ContentLanguagePreference] = None,
    sort_rule: Optional[VenueSortRule] = Query(None, alias='sortRule'),
    latitude: Optional[float] = None,
    longitude: Optional[float] = None,
    radius: Optional[float] = None,
    distance_unit: Optional[DistanceUnit] = Query(None, alias='distanceUnit'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/venues/{id}', tags=['comment_control', 'discussion_comment_moderation']
)
def delete_api_venues__id(
    id: int,
    notes: Optional[str] = '',
    hard_delete: Optional[bool] = Query(False, alias='hardDelete'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/venues/{id}/reports',
    tags=['user_reporting_service', 'venue_information_management'],
)
def post_api_venues__id_reports(
    id: int,
    report_type: Optional[VenueReportType] = Query(None, alias='reportType'),
    notes: Optional[str] = None,
    version_number: Optional[int] = Query(None, alias='versionNumber'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
