# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:48:07+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ActivityEntryOptionalFields(Enum):
    None_ = 'None'
    ArchivedVersion = 'ArchivedVersion'
    Entry = 'Entry'


class ActivityEntrySortRule(Enum):
    CreateDateDescending = 'CreateDateDescending'
    CreateDate = 'CreateDate'


class AdvancedFilterType(Enum):
    Nothing = 'Nothing'
    ArtistType = 'ArtistType'
    WebLink = 'WebLink'
    HasUserAccount = 'HasUserAccount'
    RootVoicebank = 'RootVoicebank'
    VoiceProvider = 'VoiceProvider'
    HasStoreLink = 'HasStoreLink'
    HasTracks = 'HasTracks'
    NoCoverPicture = 'NoCoverPicture'
    HasAlbum = 'HasAlbum'
    HasOriginalMedia = 'HasOriginalMedia'
    HasMedia = 'HasMedia'
    HasMultipleVoicebanks = 'HasMultipleVoicebanks'
    HasPublishDate = 'HasPublishDate'
    Lyrics = 'Lyrics'
    LyricsContent = 'LyricsContent'


class AdvancedSearchFilterParams(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filterType: Optional[AdvancedFilterType] = None
    negate: Optional[bool] = None
    param: Optional[str] = None


class AlbumIdentifierContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: Optional[str] = None


class AlbumOptionalFields(Enum):
    None_ = 'None'
    AdditionalNames = 'AdditionalNames'
    Artists = 'Artists'
    Description = 'Description'
    Discs = 'Discs'
    Identifiers = 'Identifiers'
    MainPicture = 'MainPicture'
    Names = 'Names'
    PVs = 'PVs'
    ReleaseEvent = 'ReleaseEvent'
    Tags = 'Tags'
    Tracks = 'Tracks'
    WebLinks = 'WebLinks'


class AlbumSortRule(Enum):
    None_ = 'None'
    Name = 'Name'
    ReleaseDate = 'ReleaseDate'
    ReleaseDateWithNulls = 'ReleaseDateWithNulls'
    AdditionDate = 'AdditionDate'
    RatingAverage = 'RatingAverage'
    RatingTotal = 'RatingTotal'
    NameThenReleaseDate = 'NameThenReleaseDate'
    CollectionCount = 'CollectionCount'


class ArtistAlbumParticipationStatus(Enum):
    Everything = 'Everything'
    OnlyMainAlbums = 'OnlyMainAlbums'
    OnlyCollaborations = 'OnlyCollaborations'


class ArtistCategories(Enum):
    Nothing = 'Nothing'
    Vocalist = 'Vocalist'
    Producer = 'Producer'
    Animator = 'Animator'
    Label = 'Label'
    Circle = 'Circle'
    Other = 'Other'
    Band = 'Band'
    Illustrator = 'Illustrator'
    Subject = 'Subject'


class ArtistEventRoles(Enum):
    Default = 'Default'
    Dancer = 'Dancer'
    DJ = 'DJ'
    Instrumentalist = 'Instrumentalist'
    Organizer = 'Organizer'
    Promoter = 'Promoter'
    VJ = 'VJ'
    Vocalist = 'Vocalist'
    VoiceManipulator = 'VoiceManipulator'
    OtherPerformer = 'OtherPerformer'
    Other = 'Other'


class ArtistLinkType(Enum):
    CharacterDesigner = 'CharacterDesigner'
    Group = 'Group'
    Illustrator = 'Illustrator'
    Manager = 'Manager'
    VoiceProvider = 'VoiceProvider'


class ArtistOptionalFields(Enum):
    None_ = 'None'
    AdditionalNames = 'AdditionalNames'
    ArtistLinks = 'ArtistLinks'
    ArtistLinksReverse = 'ArtistLinksReverse'
    BaseVoicebank = 'BaseVoicebank'
    Description = 'Description'
    MainPicture = 'MainPicture'
    Names = 'Names'
    Tags = 'Tags'
    WebLinks = 'WebLinks'


class ArtistRelationsFields(Enum):
    None_ = 'None'
    LatestAlbums = 'LatestAlbums'
    LatestEvents = 'LatestEvents'
    LatestSongs = 'LatestSongs'
    PopularAlbums = 'PopularAlbums'
    PopularSongs = 'PopularSongs'
    All = 'All'


class ArtistRoles(Enum):
    Default = 'Default'
    Animator = 'Animator'
    Arranger = 'Arranger'
    Composer = 'Composer'
    Distributor = 'Distributor'
    Illustrator = 'Illustrator'
    Instrumentalist = 'Instrumentalist'
    Lyricist = 'Lyricist'
    Mastering = 'Mastering'
    Publisher = 'Publisher'
    Vocalist = 'Vocalist'
    VoiceManipulator = 'VoiceManipulator'
    Other = 'Other'
    Mixer = 'Mixer'
    Chorus = 'Chorus'
    Encoder = 'Encoder'
    VocalDataProvider = 'VocalDataProvider'


class ArtistSortRule(Enum):
    None_ = 'None'
    Name = 'Name'
    AdditionDate = 'AdditionDate'
    AdditionDateAsc = 'AdditionDateAsc'
    ReleaseDate = 'ReleaseDate'
    SongCount = 'SongCount'
    SongRating = 'SongRating'
    FollowerCount = 'FollowerCount'
    ArtistType = 'ArtistType'


class ArtistType(Enum):
    Unknown = 'Unknown'
    Circle = 'Circle'
    Label = 'Label'
    Producer = 'Producer'
    Animator = 'Animator'
    Illustrator = 'Illustrator'
    Lyricist = 'Lyricist'
    Vocaloid = 'Vocaloid'
    UTAU = 'UTAU'
    CeVIO = 'CeVIO'
    OtherVoiceSynthesizer = 'OtherVoiceSynthesizer'
    OtherVocalist = 'OtherVocalist'
    OtherGroup = 'OtherGroup'
    OtherIndividual = 'OtherIndividual'
    Utaite = 'Utaite'
    Band = 'Band'
    Vocalist = 'Vocalist'
    Character = 'Character'
    SynthesizerV = 'SynthesizerV'
    CoverArtist = 'CoverArtist'


class CommentOptionalFields(Enum):
    None_ = 'None'
    Entry = 'Entry'


class CommentSortRule(Enum):
    CreateDateDescending = 'CreateDateDescending'
    CreateDate = 'CreateDate'


class ContentLanguagePreference(Enum):
    Default = 'Default'
    Japanese = 'Japanese'
    Romaji = 'Romaji'
    English = 'English'


class ContentLanguageSelection(Enum):
    Unspecified = 'Unspecified'
    Japanese = 'Japanese'
    Romaji = 'Romaji'
    English = 'English'


class DiscMediaType(Enum):
    Audio = 'Audio'
    Video = 'Video'


class DiscType(Enum):
    Unknown = 'Unknown'
    Album = 'Album'
    Single = 'Single'
    EP = 'EP'
    SplitAlbum = 'SplitAlbum'
    Compilation = 'Compilation'
    Video = 'Video'
    Artbook = 'Artbook'
    Game = 'Game'
    Fanmade = 'Fanmade'
    Instrumental = 'Instrumental'
    Other = 'Other'


class DiscussionFolderOptionalFields(Enum):
    None_ = 'None'
    LastTopic = 'LastTopic'
    TopicCount = 'TopicCount'


class DiscussionTopicOptionalFields(Enum):
    None_ = 'None'
    Comments = 'Comments'
    CommentCount = 'CommentCount'
    Content = 'Content'
    LastComment = 'LastComment'
    All = 'All'


class DiscussionTopicSortRule(Enum):
    None_ = 'None'
    Name = 'Name'
    DateCreated = 'DateCreated'
    LastCommentDate = 'LastCommentDate'


class DistanceUnit(Enum):
    Kilometers = 'Kilometers'
    Miles = 'Miles'


class EnglishTranslatedStringContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    english: Optional[str] = None
    original: Optional[str] = None


class EntryEditDataContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    time: Optional[datetime] = None
    userId: Optional[int] = None
    userName: Optional[str] = None


class EntryEditEvent(Enum):
    Created = 'Created'
    Updated = 'Updated'
    Deleted = 'Deleted'
    Restored = 'Restored'


class EntryOptionalFields(Enum):
    None_ = 'None'
    AdditionalNames = 'AdditionalNames'
    Description = 'Description'
    MainPicture = 'MainPicture'
    Names = 'Names'
    PVs = 'PVs'
    Tags = 'Tags'
    WebLinks = 'WebLinks'


class EntrySortRule(Enum):
    None_ = 'None'
    Name = 'Name'
    AdditionDate = 'AdditionDate'
    ActivityDate = 'ActivityDate'


class EntryStatus(Enum):
    Draft = 'Draft'
    Finished = 'Finished'
    Approved = 'Approved'
    Locked = 'Locked'


class EntryThumbForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mime: Optional[str] = None
    name: Optional[str] = None
    urlOriginal: Optional[str] = None
    urlSmallThumb: Optional[str] = None
    urlThumb: Optional[str] = None
    urlTinyThumb: Optional[str] = None


class EntryType(Enum):
    Undefined = 'Undefined'
    Album = 'Album'
    Artist = 'Artist'
    DiscussionTopic = 'DiscussionTopic'
    PV = 'PV'
    ReleaseEvent = 'ReleaseEvent'
    ReleaseEventSeries = 'ReleaseEventSeries'
    Song = 'Song'
    SongList = 'SongList'
    Tag = 'Tag'
    User = 'User'
    Venue = 'Venue'


class EntryTypes(Enum):
    Nothing = 'Nothing'
    Album = 'Album'
    Artist = 'Artist'
    DiscussionTopic = 'DiscussionTopic'
    PV = 'PV'
    ReleaseEvent = 'ReleaseEvent'
    ReleaseEventSeries = 'ReleaseEventSeries'
    Song = 'Song'
    SongList = 'SongList'
    Tag = 'Tag'
    User = 'User'
    Venue = 'Venue'


class EventCategory(Enum):
    Unspecified = 'Unspecified'
    AlbumRelease = 'AlbumRelease'
    Anniversary = 'Anniversary'
    Club = 'Club'
    Concert = 'Concert'
    Contest = 'Contest'
    Convention = 'Convention'
    Other = 'Other'
    Festival = 'Festival'


class EventReportType(Enum):
    InvalidInfo = 'InvalidInfo'
    Duplicate = 'Duplicate'
    Inappropriate = 'Inappropriate'
    Other = 'Other'


class EventSortRule(Enum):
    None_ = 'None'
    Name = 'Name'
    Date = 'Date'
    AdditionDate = 'AdditionDate'
    SeriesName = 'SeriesName'
    VenueName = 'VenueName'


class LocalizedStringContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    language: Optional[ContentLanguageSelection] = None
    value: Optional[str] = None


class LocalizedStringWithIdContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[int] = None
    language: Optional[ContentLanguageSelection] = None
    value: Optional[str] = None


class LogicalGrouping(Enum):
    And = 'And'
    Or = 'Or'


class MediaType(Enum):
    PhysicalDisc = 'PhysicalDisc'
    DigitalDownload = 'DigitalDownload'
    Other = 'Other'


class NameMatchMode(Enum):
    Auto = 'Auto'
    Partial = 'Partial'
    StartsWith = 'StartsWith'
    Exact = 'Exact'
    Words = 'Words'


class OldUsernameContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: Optional[datetime] = None
    oldName: Optional[str] = None


class OptionalDateTimeContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    day: Optional[int] = None
    formatted: Optional[str] = None
    isEmpty: Optional[bool] = None
    month: Optional[int] = None
    year: Optional[int] = None


class OptionalGeoPointContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    formatted: Optional[str] = None
    hasValue: Optional[bool] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None


class PVExtendedMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    json_: Optional[str] = Field(None, alias='json')


class PVService(Enum):
    NicoNicoDouga = 'NicoNicoDouga'
    Youtube = 'Youtube'
    SoundCloud = 'SoundCloud'
    Vimeo = 'Vimeo'
    Piapro = 'Piapro'
    Bilibili = 'Bilibili'
    File = 'File'
    LocalFile = 'LocalFile'
    Creofuga = 'Creofuga'
    Bandcamp = 'Bandcamp'


class PVServices(Enum):
    Nothing = 'Nothing'
    NicoNicoDouga = 'NicoNicoDouga'
    Youtube = 'Youtube'
    SoundCloud = 'SoundCloud'
    Vimeo = 'Vimeo'
    Piapro = 'Piapro'
    Bilibili = 'Bilibili'
    File = 'File'
    LocalFile = 'LocalFile'
    Creofuga = 'Creofuga'
    Bandcamp = 'Bandcamp'


class PVType(Enum):
    Original = 'Original'
    Reprint = 'Reprint'
    Other = 'Other'


class PurchaseStatus(Enum):
    Nothing = 'Nothing'
    Wishlisted = 'Wishlisted'
    Ordered = 'Ordered'
    Owned = 'Owned'


class PurchaseStatuses(Enum):
    Nothing = 'Nothing'
    Wishlisted = 'Wishlisted'
    Ordered = 'Ordered'
    Owned = 'Owned'
    All = 'All'


class RatedSongForUserSortRule(Enum):
    None_ = 'None'
    Name = 'Name'
    AdditionDate = 'AdditionDate'
    PublishDate = 'PublishDate'
    FavoritedTimes = 'FavoritedTimes'
    RatingScore = 'RatingScore'
    RatingDate = 'RatingDate'


class ReleaseEventOptionalFields(Enum):
    None_ = 'None'
    AdditionalNames = 'AdditionalNames'
    Artists = 'Artists'
    Description = 'Description'
    MainPicture = 'MainPicture'
    Names = 'Names'
    Series = 'Series'
    SongList = 'SongList'
    Tags = 'Tags'
    Venue = 'Venue'
    WebLinks = 'WebLinks'
    PVs = 'PVs'


class ReleaseEventSeriesOptionalFields(Enum):
    None_ = 'None'
    AdditionalNames = 'AdditionalNames'
    Description = 'Description'
    Events = 'Events'
    MainPicture = 'MainPicture'
    Names = 'Names'
    WebLinks = 'WebLinks'


class SongListFeaturedCategory(Enum):
    Nothing = 'Nothing'
    Concerts = 'Concerts'
    VocaloidRanking = 'VocaloidRanking'
    Pools = 'Pools'
    Other = 'Other'


class SongListOptionalFields(Enum):
    None_ = 'None'
    Description = 'Description'
    Events = 'Events'
    MainPicture = 'MainPicture'
    Tags = 'Tags'


class SongListSortRule(Enum):
    None_ = 'None'
    Name = 'Name'
    Date = 'Date'
    CreateDate = 'CreateDate'


class SongOptionalFields(Enum):
    None_ = 'None'
    AdditionalNames = 'AdditionalNames'
    Albums = 'Albums'
    Artists = 'Artists'
    Lyrics = 'Lyrics'
    MainPicture = 'MainPicture'
    Names = 'Names'
    PVs = 'PVs'
    ReleaseEvent = 'ReleaseEvent'
    Tags = 'Tags'
    ThumbUrl = 'ThumbUrl'
    WebLinks = 'WebLinks'
    Bpm = 'Bpm'


class SongSortRule(Enum):
    None_ = 'None'
    Name = 'Name'
    AdditionDate = 'AdditionDate'
    PublishDate = 'PublishDate'
    FavoritedTimes = 'FavoritedTimes'
    RatingScore = 'RatingScore'
    TagUsageCount = 'TagUsageCount'
    SongType = 'SongType'


class SongType(Enum):
    Unspecified = 'Unspecified'
    Original = 'Original'
    Remaster = 'Remaster'
    Remix = 'Remix'
    Cover = 'Cover'
    Arrangement = 'Arrangement'
    Instrumental = 'Instrumental'
    Mashup = 'Mashup'
    MusicPV = 'MusicPV'
    DramaPV = 'DramaPV'
    Live = 'Live'
    Illustration = 'Illustration'
    Other = 'Other'


class SongVocalistSelection(Enum):
    Nothing = 'Nothing'
    Vocaloid = 'Vocaloid'
    UTAU = 'UTAU'
    Other = 'Other'


class SongVoteRating(Enum):
    Nothing = 'Nothing'
    Dislike = 'Dislike'
    Like = 'Like'
    Favorite = 'Favorite'


class SortDirection(Enum):
    Ascending = 'Ascending'
    Descending = 'Descending'


class TagBaseContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    categoryName: Optional[str] = None
    id: Optional[int] = None
    name: Optional[str] = None
    urlSlug: Optional[str] = None


class TagOptionalFields(Enum):
    None_ = 'None'
    AdditionalNames = 'AdditionalNames'
    AliasedTo = 'AliasedTo'
    Description = 'Description'
    MainPicture = 'MainPicture'
    Names = 'Names'
    Parent = 'Parent'
    RelatedTags = 'RelatedTags'
    TranslatedDescription = 'TranslatedDescription'
    WebLinks = 'WebLinks'


class TagReportType(Enum):
    InvalidInfo = 'InvalidInfo'
    Duplicate = 'Duplicate'
    Inappropriate = 'Inappropriate'
    Other = 'Other'


class TagSortRule(Enum):
    Nothing = 'Nothing'
    Name = 'Name'
    AdditionDate = 'AdditionDate'
    UsageCount = 'UsageCount'


class TagTargetTypes(Enum):
    Nothing = 'Nothing'
    Album = 'Album'
    Artist = 'Artist'
    AlbumArtist = 'AlbumArtist'
    Event = 'Event'
    Song = 'Song'
    AlbumSong = 'AlbumSong'
    ArtistSong = 'ArtistSong'
    SongList = 'SongList'
    All = 'All'


class TagUsageForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    count: Optional[int] = None
    tag: Optional[TagBaseContract] = None


class TopSongsDateFilterType(Enum):
    CreateDate = 'CreateDate'
    PublishDate = 'PublishDate'
    Popularity = 'Popularity'


class TranslationType(Enum):
    Original = 'Original'
    Romanized = 'Romanized'
    Translation = 'Translation'


class UserEventRelationshipType(Enum):
    Interested = 'Interested'
    Attending = 'Attending'


class UserGroupId(Enum):
    Nothing = 'Nothing'
    Limited = 'Limited'
    Regular = 'Regular'
    Trusted = 'Trusted'
    Moderator = 'Moderator'
    Admin = 'Admin'


class UserInboxType(Enum):
    Nothing = 'Nothing'
    Received = 'Received'
    Sent = 'Sent'
    Notifications = 'Notifications'


class UserLanguageProficiency(Enum):
    Nothing = 'Nothing'
    Basics = 'Basics'
    Intermediate = 'Intermediate'
    Advanced = 'Advanced'
    Native = 'Native'


class UserOptionalFields(Enum):
    None_ = 'None'
    KnownLanguages = 'KnownLanguages'
    MainPicture = 'MainPicture'
    OldUsernames = 'OldUsernames'


class UserReportType(Enum):
    MaliciousIP = 'MaliciousIP'
    Spamming = 'Spamming'
    RemovePermissions = 'RemovePermissions'
    Other = 'Other'


class UserSortRule(Enum):
    RegisterDate = 'RegisterDate'
    Name = 'Name'
    Group = 'Group'


class VenueOptionalFields(Enum):
    None_ = 'None'
    AdditionalNames = 'AdditionalNames'
    Description = 'Description'
    Events = 'Events'
    Names = 'Names'
    WebLinks = 'WebLinks'


class VenueReportType(Enum):
    InvalidInfo = 'InvalidInfo'
    Duplicate = 'Duplicate'
    Inappropriate = 'Inappropriate'
    Other = 'Other'


class VenueSortRule(Enum):
    None_ = 'None'
    Name = 'Name'
    Distance = 'Distance'


class WebLinkCategory(Enum):
    Official = 'Official'
    Commercial = 'Commercial'
    Reference = 'Reference'
    Other = 'Other'


class WebLinkContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    category: Optional[WebLinkCategory] = None
    description: Optional[str] = None
    descriptionOrUrl: Optional[str] = None
    disabled: Optional[bool] = None
    id: Optional[int] = None
    url: Optional[str] = None


class WebLinkForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    category: Optional[WebLinkCategory] = None
    description: Optional[str] = None
    descriptionOrUrl: Optional[str] = None
    disabled: Optional[bool] = None
    id: Optional[int] = None
    url: Optional[str] = None


class TagName(RootModel[List[str]]):
    root: List[str]


class TagId(RootModel[List[int]]):
    root: List[int]


class ArtistId(RootModel[List[int]]):
    root: List[int]


class AdvancedFilters(RootModel[List[AdvancedSearchFilterParams]]):
    root: List[AdvancedSearchFilterParams]


class ApiAlbumsNamesGetResponse(RootModel[List[str]]):
    root: List[str]


class IgnoreIds(RootModel[List[int]]):
    root: List[int]


class ApiAlbumsIdTracksFieldsGetResponse(RootModel[List[Dict[str, str]]]):
    root: List[Dict[str, str]]


class FieldModel(RootModel[List[str]]):
    root: List[str]


class ApiArtistsNamesGetResponse(RootModel[List[str]]):
    root: List[str]


class ApiEntriesNamesGetResponse(RootModel[List[str]]):
    root: List[str]


class ApiReleaseEventsNamesGetResponse(RootModel[List[str]]):
    root: List[str]


class ApiResourcesCultureCodeGetResponse(
    RootModel[Optional[Dict[str, Dict[str, str]]]]
):
    root: Optional[Dict[str, Dict[str, str]]] = None


class SetNames(RootModel[List[str]]):
    root: List[str]


class ApiSongListsFeaturedNamesGetResponse(RootModel[List[str]]):
    root: List[str]


class ApiSongsNamesGetResponse(RootModel[List[str]]):
    root: List[str]


class ApiTagsCategoryNamesGetResponse(RootModel[List[str]]):
    root: List[str]


class ApiTagsNamesGetResponse(RootModel[List[str]]):
    root: List[str]


class ApiTagsTopGetResponse(RootModel[List[TagBaseContract]]):
    root: List[TagBaseContract]


class ApiUsersNamesGetResponse(RootModel[List[str]]):
    root: List[str]


class MessageId(RootModel[List[int]]):
    root: List[int]


class AlbumDiscPropertiesContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    discNumber: Optional[int] = None
    id: Optional[int] = None
    mediaType: Optional[DiscMediaType] = None
    name: Optional[str] = None


class ArchivedWebLinkContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    category: Optional[WebLinkCategory] = None
    description: Optional[str] = None
    disabled: Optional[bool] = None
    url: Optional[str] = None


class ArtistContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    artistType: Optional[ArtistType] = None
    deleted: Optional[bool] = None
    id: Optional[int] = None
    name: Optional[str] = None
    pictureMime: Optional[str] = None
    releaseDate: Optional[datetime] = None
    status: Optional[EntryStatus] = None
    version: Optional[int] = None


class ArtistForAlbumForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artist: Optional[ArtistContract] = None
    categories: Optional[ArtistCategories] = None
    effectiveRoles: Optional[ArtistRoles] = None
    isSupport: Optional[bool] = None
    name: Optional[str] = None
    roles: Optional[ArtistRoles] = None


class ArtistForArtistForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artist: Optional[ArtistContract] = None
    linkType: Optional[ArtistLinkType] = None


class ArtistForEventContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artist: Optional[ArtistContract] = None
    effectiveRoles: Optional[ArtistEventRoles] = None
    id: Optional[int] = None
    name: Optional[str] = None
    roles: Optional[ArtistEventRoles] = None


class ArtistForSongContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artist: Optional[ArtistContract] = None
    categories: Optional[ArtistCategories] = None
    effectiveRoles: Optional[ArtistRoles] = None
    id: Optional[int] = None
    isCustomName: Optional[bool] = None
    isSupport: Optional[bool] = None
    name: Optional[str] = None
    roles: Optional[ArtistRoles] = None


class CreateReportModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reason: Optional[str] = None
    reportType: Optional[UserReportType] = None


class LyricsForSongContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cultureCode: Optional[str] = ''
    id: Optional[int] = None
    source: Optional[str] = ''
    translationType: Optional[TranslationType] = None
    url: Optional[str] = ''
    value: Optional[str] = None


class PVContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    author: Optional[str] = None
    createdBy: Optional[int] = None
    disabled: Optional[bool] = None
    extendedMetadata: Optional[PVExtendedMetadata] = None
    id: Optional[int] = None
    length: Optional[int] = None
    name: Optional[str] = None
    publishDate: Optional[datetime] = None
    pvId: Optional[str] = None
    pvType: Optional[PVType] = None
    service: Optional[PVService] = None
    thumbUrl: Optional[str] = None
    url: Optional[str] = None


class ReleaseEventSeriesContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    category: Optional[EventCategory] = None
    deleted: Optional[bool] = None
    description: Optional[str] = None
    id: Optional[int] = None
    name: Optional[str] = None
    pictureMime: Optional[str] = None
    status: Optional[EntryStatus] = None
    urlSlug: Optional[str] = None
    version: Optional[int] = None
    webLinks: Optional[List[WebLinkContract]] = None


class ReleaseEventSeriesForEditForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    category: Optional[EventCategory] = None
    defaultNameLanguage: Optional[ContentLanguageSelection] = None
    deleted: Optional[bool] = None
    description: Optional[str] = None
    id: Optional[int] = None
    mainPicture: Optional[EntryThumbForApiContract] = None
    name: Optional[str] = None
    names: Optional[List[LocalizedStringWithIdContract]] = None
    status: Optional[EntryStatus] = None
    webLinks: Optional[List[WebLinkForApiContract]] = None


class SongContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    artistString: Optional[str] = None
    createDate: Optional[datetime] = None
    deleted: Optional[bool] = None
    favoritedTimes: Optional[int] = None
    id: Optional[int] = None
    lengthSeconds: Optional[int] = None
    name: Optional[str] = None
    nicoId: Optional[str] = None
    publishDate: Optional[datetime] = None
    pvServices: Optional[PVServices] = None
    ratingScore: Optional[int] = None
    songType: Optional[SongType] = None
    status: Optional[EntryStatus] = None
    thumbUrl: Optional[str] = None
    version: Optional[int] = None


class SongListBaseContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    featuredCategory: Optional[SongListFeaturedCategory] = None
    id: Optional[int] = None
    name: Optional[str] = None


class SongRatingContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rating: Optional[SongVoteRating] = None


class TagForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    aliasedTo: Optional[TagBaseContract] = None
    categoryName: Optional[str] = None
    createDate: Optional[datetime] = None
    defaultNameLanguage: Optional[ContentLanguageSelection] = None
    description: Optional[str] = None
    id: Optional[int] = None
    mainPicture: Optional[EntryThumbForApiContract] = None
    name: Optional[str] = None
    names: Optional[List[LocalizedStringWithIdContract]] = None
    parent: Optional[TagBaseContract] = None
    relatedTags: Optional[List[TagBaseContract]] = None
    status: Optional[EntryStatus] = None
    targets: Optional[int] = None
    translatedDescription: Optional[EnglishTranslatedStringContract] = None
    urlSlug: Optional[str] = None
    usageCount: Optional[int] = None
    version: Optional[int] = None
    webLinks: Optional[List[WebLinkForApiContract]] = None


class TagForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[TagForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class UserKnownLanguageContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cultureCode: Optional[str] = None
    proficiency: Optional[UserLanguageProficiency] = None


class VenueContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    address: Optional[str] = None
    addressCountryCode: Optional[str] = None
    coordinates: Optional[OptionalGeoPointContract] = None
    deleted: Optional[bool] = None
    description: Optional[str] = None
    id: Optional[int] = None
    name: Optional[str] = None
    status: Optional[EntryStatus] = None
    version: Optional[int] = None
    webLinks: Optional[List[WebLinkContract]] = None


class ApiTagsTagIdChildrenGetResponse(RootModel[List[TagForApiContract]]):
    root: List[TagForApiContract]


class EntryForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activityDate: Optional[datetime] = None
    additionalNames: Optional[str] = None
    artistString: Optional[str] = None
    artistType: Optional[ArtistType] = None
    createDate: Optional[datetime] = None
    defaultName: Optional[str] = None
    defaultNameLanguage: Optional[ContentLanguageSelection] = None
    description: Optional[str] = None
    discType: Optional[DiscType] = None
    entryType: Optional[EntryType] = None
    eventCategory: Optional[EventCategory] = None
    id: Optional[int] = None
    mainPicture: Optional[EntryThumbForApiContract] = None
    name: Optional[str] = None
    names: Optional[List[LocalizedStringContract]] = None
    pvs: Optional[List[PVContract]] = None
    releaseEventSeriesName: Optional[str] = None
    songListFeaturedCategory: Optional[SongListFeaturedCategory] = None
    songType: Optional[SongType] = None
    status: Optional[EntryStatus] = None
    tagCategoryName: Optional[str] = None
    tags: Optional[List[TagUsageForApiContract]] = None
    urlSlug: Optional[str] = None
    version: Optional[int] = None
    webLinks: Optional[List[ArchivedWebLinkContract]] = None


class EntryForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[EntryForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class PVForSongContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    author: Optional[str] = None
    createdBy: Optional[int] = None
    disabled: Optional[bool] = None
    extendedMetadata: Optional[PVExtendedMetadata] = None
    id: Optional[int] = None
    length: Optional[int] = None
    name: Optional[str] = None
    publishDate: Optional[datetime] = None
    pvId: Optional[str] = None
    pvType: Optional[PVType] = None
    service: Optional[PVService] = None
    song: Optional[SongContract] = None
    thumbUrl: Optional[str] = None
    url: Optional[str] = None


class PVForSongContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[PVForSongContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class ReleaseEventContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    category: Optional[EventCategory] = None
    customName: Optional[bool] = None
    date: Optional[datetime] = None
    deleted: Optional[bool] = None
    description: Optional[str] = None
    endDate: Optional[datetime] = None
    hasVenueOrVenueName: Optional[bool] = None
    id: Optional[int] = None
    inheritedCategory: Optional[EventCategory] = None
    name: Optional[str] = None
    pictureMime: Optional[str] = None
    series: Optional[ReleaseEventSeriesContract] = None
    songList: Optional[SongListBaseContract] = None
    status: Optional[EntryStatus] = None
    urlSlug: Optional[str] = None
    venue: Optional[VenueContract] = None
    venueName: Optional[str] = None
    version: Optional[int] = None


class UserForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    active: Optional[bool] = None
    groupId: Optional[UserGroupId] = None
    id: Optional[int] = None
    knownLanguages: Optional[List[UserKnownLanguageContract]] = None
    mainPicture: Optional[EntryThumbForApiContract] = None
    memberSince: Optional[datetime] = None
    name: Optional[str] = None
    oldUsernames: Optional[List[OldUsernameContract]] = None
    verifiedArtist: Optional[bool] = None


class UserForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[UserForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class UserMessageContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    body: Optional[str] = None
    createdFormatted: Optional[str] = None
    highPriority: Optional[bool] = None
    id: Optional[int] = None
    inbox: Optional[UserInboxType] = None
    read: Optional[bool] = None
    receiver: Optional[UserForApiContract] = None
    sender: Optional[UserForApiContract] = None
    subject: Optional[str] = None


class UserMessageContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[UserMessageContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class VenueForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    address: Optional[str] = None
    addressCountryCode: Optional[str] = None
    coordinates: Optional[OptionalGeoPointContract] = None
    deleted: Optional[bool] = None
    description: Optional[str] = None
    events: Optional[List[ReleaseEventContract]] = None
    id: Optional[int] = None
    name: Optional[str] = None
    names: Optional[List[LocalizedStringContract]] = None
    status: Optional[EntryStatus] = None
    version: Optional[int] = None
    webLinks: Optional[List[WebLinkForApiContract]] = None


class VenueForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[VenueForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class AlbumReviewContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    albumId: Optional[int] = None
    date: Optional[datetime] = None
    id: Optional[int] = None
    languageCode: Optional[str] = None
    text: Optional[str] = None
    title: Optional[str] = None
    user: Optional[UserForApiContract] = None


class ArchivedObjectVersionForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agentName: Optional[str] = None
    anythingChanged: Optional[bool] = None
    author: Optional[UserForApiContract] = None
    changedFields: Optional[List[str]] = None
    created: Optional[datetime] = None
    hidden: Optional[bool] = None
    id: Optional[int] = None
    isSnapshot: Optional[bool] = None
    notes: Optional[str] = None
    reason: Optional[str] = None
    status: Optional[EntryStatus] = None
    version: Optional[int] = None


class CommentForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    author: Optional[UserForApiContract] = None
    authorName: Optional[str] = None
    created: Optional[datetime] = None
    entry: Optional[EntryForApiContract] = None
    id: Optional[int] = None
    message: Optional[str] = None


class CommentForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[CommentForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class DiscussionFolderContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Optional[str] = None
    id: Optional[int] = None
    lastTopicAuthor: Optional[UserForApiContract] = None
    lastTopicDate: Optional[datetime] = None
    name: Optional[str] = None
    topicCount: Optional[int] = None


class DiscussionTopicContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    author: Optional[UserForApiContract] = None
    commentCount: Optional[int] = None
    comments: Optional[List[CommentForApiContract]] = None
    content: Optional[str] = None
    created: Optional[datetime] = None
    folderId: Optional[int] = None
    id: Optional[int] = None
    lastComment: Optional[CommentForApiContract] = None
    locked: Optional[bool] = None
    name: Optional[str] = None


class DiscussionTopicContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[DiscussionTopicContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class ReleaseEventForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    artists: Optional[List[ArtistForEventContract]] = None
    category: Optional[EventCategory] = None
    date: Optional[datetime] = None
    description: Optional[str] = None
    endDate: Optional[datetime] = None
    id: Optional[int] = None
    mainPicture: Optional[EntryThumbForApiContract] = None
    name: Optional[str] = None
    names: Optional[List[LocalizedStringContract]] = None
    pvs: Optional[List[PVContract]] = None
    series: Optional[ReleaseEventSeriesContract] = None
    seriesId: Optional[int] = None
    seriesNumber: Optional[int] = None
    seriesSuffix: Optional[str] = None
    songList: Optional[SongListBaseContract] = None
    status: Optional[EntryStatus] = None
    tags: Optional[List[TagUsageForApiContract]] = None
    urlSlug: Optional[str] = None
    venue: Optional[VenueForApiContract] = None
    venueName: Optional[str] = None
    version: Optional[int] = None
    webLinks: Optional[List[WebLinkForApiContract]] = None


class ReleaseEventForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[ReleaseEventForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class ReleaseEventSeriesForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    category: Optional[EventCategory] = None
    description: Optional[str] = None
    events: Optional[List[ReleaseEventForApiContract]] = None
    id: Optional[int] = None
    mainPicture: Optional[EntryThumbForApiContract] = None
    name: Optional[str] = None
    names: Optional[List[LocalizedStringContract]] = None
    status: Optional[EntryStatus] = None
    urlSlug: Optional[str] = None
    version: Optional[int] = None
    webLinks: Optional[List[WebLinkForApiContract]] = None


class ReleaseEventSeriesForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[ReleaseEventSeriesForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class SongListForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    author: Optional[UserForApiContract] = None
    deleted: Optional[bool] = None
    description: Optional[str] = None
    eventDate: Optional[datetime] = None
    events: Optional[List[ReleaseEventForApiContract]] = None
    featuredCategory: Optional[SongListFeaturedCategory] = None
    id: Optional[int] = None
    latestComments: Optional[List[CommentForApiContract]] = None
    mainPicture: Optional[EntryThumbForApiContract] = None
    name: Optional[str] = None
    status: Optional[EntryStatus] = None
    tags: Optional[List[TagUsageForApiContract]] = None


class SongListForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[SongListForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class ApiAlbumsIdCommentsGetResponse(RootModel[List[CommentForApiContract]]):
    root: List[CommentForApiContract]


class ApiAlbumsIdReviewsGetResponse(RootModel[List[AlbumReviewContract]]):
    root: List[AlbumReviewContract]


class ApiArtistsIdCommentsGetResponse(RootModel[List[CommentForApiContract]]):
    root: List[CommentForApiContract]


class ApiDiscussionsFoldersGetResponse(RootModel[List[DiscussionFolderContract]]):
    root: List[DiscussionFolderContract]


class ApiDiscussionsFoldersFolderIdTopicsGetResponse(
    RootModel[List[DiscussionTopicContract]]
):
    root: List[DiscussionTopicContract]


class ApiSongsIdCommentsGetResponse(RootModel[List[CommentForApiContract]]):
    root: List[CommentForApiContract]


class ApiUsersIdEventsGetResponse(RootModel[List[ReleaseEventForApiContract]]):
    root: List[ReleaseEventForApiContract]


class ActivityEntryForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    archivedVersion: Optional[ArchivedObjectVersionForApiContract] = None
    author: Optional[UserForApiContract] = None
    createDate: Optional[datetime] = None
    editEvent: Optional[EntryEditEvent] = None
    entry: Optional[EntryForApiContract] = None


class ActivityEntryForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[ActivityEntryForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class AlbumContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    artistString: Optional[str] = None
    coverPictureMime: Optional[str] = None
    createDate: Optional[datetime] = None
    deleted: Optional[bool] = None
    discType: Optional[DiscType] = None
    id: Optional[int] = None
    name: Optional[str] = None
    ratingAverage: Optional[float] = None
    ratingCount: Optional[int] = None
    releaseDate: Optional[OptionalDateTimeContract] = None
    releaseEvent: Optional[ReleaseEventForApiContract] = None
    status: Optional[EntryStatus] = None
    version: Optional[int] = None


class SongForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    albums: Optional[List[AlbumContract]] = None
    artistString: Optional[str] = None
    artists: Optional[List[ArtistForSongContract]] = None
    createDate: Optional[datetime] = None
    defaultName: Optional[str] = None
    defaultNameLanguage: Optional[ContentLanguageSelection] = None
    deleted: Optional[bool] = None
    favoritedTimes: Optional[int] = None
    id: Optional[int] = None
    lengthSeconds: Optional[int] = None
    lyrics: Optional[List[LyricsForSongContract]] = None
    mainPicture: Optional[EntryThumbForApiContract] = None
    maxMilliBpm: Optional[int] = None
    mergedTo: Optional[int] = None
    minMilliBpm: Optional[int] = None
    name: Optional[str] = None
    names: Optional[List[LocalizedStringContract]] = None
    originalVersionId: Optional[int] = None
    publishDate: Optional[datetime] = None
    pvServices: Optional[PVServices] = None
    pvs: Optional[List[PVContract]] = None
    ratingScore: Optional[int] = None
    releaseEvent: Optional[ReleaseEventForApiContract] = None
    songType: Optional[SongType] = None
    status: Optional[EntryStatus] = None
    tags: Optional[List[TagUsageForApiContract]] = None
    thumbUrl: Optional[str] = None
    version: Optional[int] = None
    webLinks: Optional[List[WebLinkForApiContract]] = None


class SongForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[SongForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class SongInAlbumForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    discNumber: Optional[int] = None
    id: Optional[int] = None
    name: Optional[str] = None
    rating: Optional[SongVoteRating] = None
    song: Optional[SongForApiContract] = None
    trackNumber: Optional[int] = None


class SongInListEditContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    notes: Optional[str] = None
    order: Optional[int] = None
    song: Optional[SongForApiContract] = None
    songInListId: Optional[int] = None


class SongInListForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    notes: Optional[str] = None
    order: Optional[int] = None
    song: Optional[SongForApiContract] = None


class SongInListForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[SongInListForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class SongListForEditForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    deleted: Optional[bool] = None
    description: Optional[str] = None
    eventDate: Optional[datetime] = None
    featuredCategory: Optional[SongListFeaturedCategory] = None
    id: Optional[int] = None
    mainPicture: Optional[EntryThumbForApiContract] = None
    name: Optional[str] = None
    songLinks: Optional[List[SongInListEditContract]] = None
    status: Optional[EntryStatus] = None
    updateNotes: Optional[str] = None


class ApiAlbumsIdTracksGetResponse(RootModel[List[SongInAlbumForApiContract]]):
    root: List[SongInAlbumForApiContract]


class ApiReleaseEventsEventIdPublishedSongsGetResponse(
    RootModel[List[SongForApiContract]]
):
    root: List[SongForApiContract]


class ApiSongsHighlightedGetResponse(RootModel[List[SongForApiContract]]):
    root: List[SongForApiContract]


class ApiSongsTopRatedGetResponse(RootModel[List[SongForApiContract]]):
    root: List[SongForApiContract]


class ApiSongsIdDerivedGetResponse(RootModel[List[SongForApiContract]]):
    root: List[SongForApiContract]


class AlbumForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    artistString: Optional[str] = None
    artists: Optional[List[ArtistForAlbumForApiContract]] = None
    barcode: Optional[str] = None
    catalogNumber: Optional[str] = None
    createDate: Optional[datetime] = None
    defaultName: Optional[str] = None
    defaultNameLanguage: Optional[ContentLanguageSelection] = None
    deleted: Optional[bool] = None
    description: Optional[str] = None
    discType: Optional[DiscType] = None
    discs: Optional[List[AlbumDiscPropertiesContract]] = None
    id: Optional[int] = None
    identifiers: Optional[List[AlbumIdentifierContract]] = None
    mainPicture: Optional[EntryThumbForApiContract] = None
    mergedTo: Optional[int] = None
    name: Optional[str] = None
    names: Optional[List[LocalizedStringContract]] = None
    pvs: Optional[List[PVContract]] = None
    ratingAverage: Optional[float] = None
    ratingCount: Optional[int] = None
    releaseDate: Optional[OptionalDateTimeContract] = None
    releaseEvent: Optional[ReleaseEventForApiContract] = None
    status: Optional[EntryStatus] = None
    tags: Optional[List[TagUsageForApiContract]] = None
    tracks: Optional[List[SongInAlbumForApiContract]] = None
    version: Optional[int] = None
    webLinks: Optional[List[WebLinkForApiContract]] = None


class AlbumForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[AlbumForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class AlbumForUserForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    album: Optional[AlbumForApiContract] = None
    mediaType: Optional[MediaType] = None
    purchaseStatus: Optional[PurchaseStatus] = None
    rating: Optional[int] = None
    user: Optional[UserForApiContract] = None


class AlbumForUserForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[AlbumForUserForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class ArtistRelationsForApi(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    latestAlbums: Optional[List[AlbumForApiContract]] = None
    latestEvents: Optional[List[ReleaseEventForApiContract]] = None
    latestSongs: Optional[List[SongForApiContract]] = None
    popularAlbums: Optional[List[AlbumForApiContract]] = None
    popularSongs: Optional[List[SongForApiContract]] = None


class RatedSongForUserForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: Optional[datetime] = None
    rating: Optional[SongVoteRating] = None
    song: Optional[SongForApiContract] = None
    user: Optional[UserForApiContract] = None


class RatedSongForUserForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[RatedSongForUserForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class RelatedSongsContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artistMatches: Optional[List[SongForApiContract]] = None
    likeMatches: Optional[List[SongForApiContract]] = None
    tagMatches: Optional[List[SongForApiContract]] = None


class ApiAlbumsNewGetResponse(RootModel[List[AlbumForApiContract]]):
    root: List[AlbumForApiContract]


class ApiAlbumsTopGetResponse(RootModel[List[AlbumForApiContract]]):
    root: List[AlbumForApiContract]


class ApiAlbumsIdUserCollectionsGetResponse(
    RootModel[List[AlbumForUserForApiContract]]
):
    root: List[AlbumForUserForApiContract]


class ApiReleaseEventsEventIdAlbumsGetResponse(RootModel[List[AlbumForApiContract]]):
    root: List[AlbumForApiContract]


class ApiSongsIdRatingsGetResponse(RootModel[List[RatedSongForUserForApiContract]]):
    root: List[RatedSongForUserForApiContract]


class ArtistForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    additionalNames: Optional[str] = None
    artistLinks: Optional[List[ArtistForArtistForApiContract]] = None
    artistLinksReverse: Optional[List[ArtistForArtistForApiContract]] = None
    artistType: Optional[ArtistType] = None
    baseVoicebank: Optional[ArtistContract] = None
    createDate: Optional[datetime] = None
    defaultName: Optional[str] = None
    defaultNameLanguage: Optional[ContentLanguageSelection] = None
    deleted: Optional[bool] = None
    description: Optional[str] = None
    id: Optional[int] = None
    mainPicture: Optional[EntryThumbForApiContract] = None
    mergedTo: Optional[int] = None
    name: Optional[str] = None
    names: Optional[List[LocalizedStringContract]] = None
    pictureMime: Optional[str] = None
    relations: Optional[ArtistRelationsForApi] = None
    releaseDate: Optional[datetime] = None
    status: Optional[EntryStatus] = None
    tags: Optional[List[TagUsageForApiContract]] = None
    version: Optional[int] = None
    webLinks: Optional[List[WebLinkForApiContract]] = None


class ArtistForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[ArtistForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None


class ArtistForUserForApiContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artist: Optional[ArtistForApiContract] = None
    id: Optional[int] = None


class ArtistForUserForApiContractPartialFindResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Optional[List[ArtistForUserForApiContract]] = None
    term: Optional[str] = None
    totalCount: Optional[int] = None
